### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by prisonerjohn**
Hey, awesome work on this addon, it's super useful! I found a few issues and omissions I fixed.

### CODE REVIEW

**Comment by memo** [comment]
Hey, thanks for doing this! I haven't tested the code, but looking through the commits it generally looks good except for a small thing which caused a little bit of concern:

* you've added (string options = "",) as a second parameter to loadProgramFromFile (in both Opencl and OpenclProgram) . This will break backwards compatibility, because if the second parameter isBinary was used, now the isBinary flag will be passed in as the string. For backwards compatibility sake it could be better to have the new parameter at the end? what do you think?

**Comment by prisonerjohn** [comment]
Good point, I'll change that and update.

**Comment by prisonerjohn** [comment]
Should be good now!

**Comment by memo** [comment]
ace thx, looks good! out of curiosity, what kind of options do you use with this?

**Comment by prisonerjohn** [comment]
Cool!

I ported over [this Marching Cubes implementation](http://www.eriksmistad.no/marching-cubes-implementation-using-opencl-and-opengl/), and resolution is passed in to figure out [how many Histogram Pyramids](https://github.com/smistad/GPU-Marching-Cubes/blob/master/gpu-mc.cl#L389-L400) to generate.

**Comment by prisonerjohn** [comment]
(Did you mean to close without merging?)

**Comment by memo** [comment]
doh, no i didn't mean to close without merging. juggling a million plates at once :/
the marching cubes thing looks ace. if you want to submit it as an example pls go ahead :)

**Comment by prisonerjohn** [comment]
Cool, I was planning on it, just trying to up the framerate a bit first ;)

**Pull request merged**
